level: "info"

redis_uri: "redis://username:password@url/db"

conn_uri: "127.0.0.1:5556"

conn_type: "tcp"

cookie_domain: "example.com"

twitch_redirect_uri: "https://example.com/login/callback"

twitch_client_id: "9l0csbymcwn2ilun4h2tj00srciium"

twitch_client_secret: "3ni2rw6q555zoihxri5ca3gaj4k8ql"

website_url: "https://example.com"

discord_invite: "https://discord.com/api/oauth2/authorize?client_id=&permissions=8&scope=bot%20applications.commands"

discord_bot_token: ""

admins:
  - "discord-user-id"
